-- begin ENTITYINSPECTOR_FIRST_ISSUE_B
alter table ENTITYINSPECTOR_FIRST_ISSUE_B add constraint FK_ENTITYINSPECTOR_FIRST_ISSUE_B_FIRST_ISSUE_A foreign key (FIRST_ISSUE_A_ID) references ENTITYINSPECTOR_FIRST_ISSUE_A(ID)^
alter table ENTITYINSPECTOR_FIRST_ISSUE_B add constraint FK_ENTITYINSPECTOR_FIRST_ISSUE_B_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ENTITYINSPECTOR_FIRST_ISSUE_B_FIRST_ISSUE_A on ENTITYINSPECTOR_FIRST_ISSUE_B (FIRST_ISSUE_A_ID)^
create index IDX_ENTITYINSPECTOR_FIRST_ISSUE_B_USER on ENTITYINSPECTOR_FIRST_ISSUE_B (USER_ID)^
-- end ENTITYINSPECTOR_FIRST_ISSUE_B
-- begin ENTITYINSPECTOR_SECOND_ISSUE
alter table ENTITYINSPECTOR_SECOND_ISSUE add constraint FK_ENTITYINSPECTOR_SECOND_ISSUE_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ENTITYINSPECTOR_SECOND_ISSUE_USER on ENTITYINSPECTOR_SECOND_ISSUE (USER_ID)^
-- end ENTITYINSPECTOR_SECOND_ISSUE
